apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: qro.ocir.io/ax6svbbnc2oh/registry-front-nginx:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:  
      - name: ocirsecret  

---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react-frontend

